docs: change `tutor dev init` to `tutor dev do init` in plugin setup (#104)
per breaking change in v15.0.0: https://github.com/overhangio/tutor/blob/master/CHANGELOG.md#v1500-2022-12-06

Without this change, the line:

    tutor dev init -l library_authoring_mfe

would fail with:

    Usage: tutor dev [OPTIONS] COMMAND [ARGS]...
    Try 'tutor dev -h' for help.

    Error: No such command 'init'.